package co.mv.stm;

import java.util.UUID;

public interface AssertionResult
{
	/**
	 * Returns the ID of the {@link co.mv.stm.model.Assertion} that was tested.
	 * 
	 * @return                          the ID of the Assertion that this result was generated from.
	 * @since                           1.0.0
	 */
	UUID getAssertionId();
	
	/**
	 * Returns the result of the {@link co.mv.stm.model.Assertion}.  The Assertion either passed or it failed.
	 * 
	 * @return                          the result of the Assertion.
	 * @since                           1.0.0
	 */
	boolean getResult();
	
	/**
	 * Returns the message that was generated by the {@link co.mv.stm.model.Assertion} to go along with the boolean
	 * result.
	 * 
	 * @return                          the message that was generated by the Assertion.
	 * @since                           1.0.0
	 */
	String getMessage();
}
